name: RevolutionarySince95
favicon: null
layout_spectrum: 0.23699
typography_spectrum: 0.68137
title: A glimpse into the mind of Davis Carbo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.7427389831282198
  saturation: 0.4908512115944177
  rhythmicContrast: 0.9536848601419479
purpose: []
