name: RevolutionarySince95
favicon: null
layout_spectrum: 0.98458
typography_spectrum: 0.4386
title: A glimpse into the mind of Davis Carbo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.4908512115944177
  rhythmicContrast: 0.75
purpose: []
